apiVersion: v1
name: harbor
version: 1.3.2
appVersion: 1.10.2
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
home: https://goharbor.io
icon: https://markdown-1300017440.cos.ap-shanghai.myqcloud.com/mweb/harbor.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
maintainers:
- name: Wenkai Yin
  email: yinw@vmware.com
- name: Weiwei He
  email: hweiwei@vmware.com
engine: gotpl
