apiVersion: apps/v1
kind: Deployment
  labels:
    app: hello-wrold
    charts: demo-charts
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.pullpolicy }}
        name: hello-world-container
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
