apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    charts: demo-charts
  name: {{ .Values.app.name }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: {{ .Values.service.type }}
