apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
    build: "13"
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: harbor.youjiqing.club/rancher/nginx:13
        imagePullPolicy: {{ .Values.deployment.pullpolicy }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
