app:
  name: pipeline-html

deployment:
  replicas: "1"
  pullpolicy: IfNotPresent
  image: harbor.youjiqing.club/rancher/pipeline-html:4

service:
  type: ClusterIP

ingress:
  host: pipeline.youjiqing.xyz
