{{- $res := .Values.persistence.persistentVolumeClaim -}}
{{- if and .Values.persistence.enabled (not $res.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    app: online-res
    charts: online-res
spec:
  accessModes: 
    - {{ $res.accessMode }}
  resources:
    requests:
      storage: {{ $res.size }}
  storageClassName: {{ $res.storageClass }}
{{- end }}
