apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    charts: demo-charts
  name: {{ .Values.app.name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
